-- H2 데이터베이스 초기 데이터 삽입
-- 테스트 아이템 더미 데이터

INSERT INTO test_items (name, category, created_at, updated_at) VALUES
('노트북', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('마우스', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('키보드', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('모니터', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('책상', '가구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('의자', '가구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('램프', '가구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('볼펜', '문구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('노트', '문구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('지우개', '문구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('필통', '문구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('헤드셋', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('스피커', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('웹캠', '전자제품', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('책장', '가구', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
